"""phase1: users namespaces nodes versions tags logs

Revision ID: 265a5825601b
Revises: 
Create Date: 2026-03-16 20:00:46.571786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265a5825601b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('namespaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespaces_slug'), 'namespaces', ['slug'], unique=True)
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('namespace_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'namespace_id', name='uq_node_name_namespace')
    )
    op.create_index(op.f('ix_nodes_category'), 'nodes', ['category'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=False)
    op.create_index(op.f('ix_nodes_status'), 'nodes', ['status'], unique=False)
    op.create_index(op.f('ix_nodes_type'), 'nodes', ['type'], unique=False)
    op.create_table('node_invocation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('invoked_by', sa.UUID(), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoked_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invocation_logs_node_created', 'node_invocation_logs', ['node_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_node_invocation_logs_created_at'), 'node_invocation_logs', ['created_at'], unique=False)
    op.create_table('node_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'tag', name='uq_node_tag')
    )
    op.create_index(op.f('ix_node_tags_node_id'), 'node_tags', ['node_id'], unique=False)
    op.create_index(op.f('ix_node_tags_tag'), 'node_tags', ['tag'], unique=False)
    op.create_table('node_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runtime_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('node_id', 'version', name='uq_node_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_versions')
    op.drop_index(op.f('ix_node_tags_tag'), table_name='node_tags')
    op.drop_index(op.f('ix_node_tags_node_id'), table_name='node_tags')
    op.drop_table('node_tags')
    op.drop_index(op.f('ix_node_invocation_logs_created_at'), table_name='node_invocation_logs')
    op.drop_index('ix_invocation_logs_node_created', table_name='node_invocation_logs')
    op.drop_table('node_invocation_logs')
    op.drop_index(op.f('ix_nodes_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_status'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_category'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_namespaces_slug'), table_name='namespaces')
    op.drop_table('namespaces')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
