"""phase2_add_invocation_count

Revision ID: c74a3f043f03
Revises: 265a5825601b
Create Date: 2026-03-17 13:57:01.691891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c74a3f043f03'
down_revision: Union[str, None] = '265a5825601b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('invocation_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'invocation_count')
    # ### end Alembic commands ###
